### ISSUE TITLE
What works and what doesn't on your model: please report here

### ISSUE THREAD

**Issue by GeographicCone** [GeographicCone/OmenHwCtl#1]
In this issue, please report if the script works for you or not.
Template:

----

* Device: **Model Name & Version** ([Device List](https://github.com/GeographicCone/OmenHwCtl/blob/master/Reference/Bundled/HP.Omen.Core.Model.Device.JSON.DeviceList.json))
* Script Version: **YYYY-MM-DD**
* Working:
  * _[...]_
* Not Working
  * _[...]_

````markdown
* Device: **Model Name & Version (Year, AMD | AMD/nVidia | Intel/nVidia)**
* Script Version: **YYYY-MM-DD**
* Working:
  * [Please list what you tried that worked]
* Not Working:
  * [Please list what you tried that did not work]
````
----
_**2023-08-15** Template updated  as there are now many more operations implemented, and the entirety of them is unlikely to work on any single device._

**Comment by GeographicCone** [comment]
* Device **Omen 16-b1xxxx (2022, Intel/nVidia)**
* Version: **2023-08-10**
* **All** Working

**Comment by cuhpoftea** [comment]
* Device: **Omen 16-b0000 (2021, Intel/nVidia)**
* Version: **2023-08-11**
* **All** Working

**Comment by dd871** [comment]
Sorry, this is going to be a bit longer, but thought I provide some feedback on a different model

- Device Omen 17-ck2xxx (2023, Intel/nVidia)
- Version: 2023-08-12
- Partially working:

This is a fairly new laptop, hence I did not try to do any "set" commands, as I am afraid I might break something. But based on the "get" commands, there are definitely some differences already.

- GetBacklight: Not working. Just outputs zero's, no matter if on or off
- GetBacklightSupport: Returns 063a0000
- GetBornOnDate: Working
- GetColorTable: Seems to return values that match the description, but if I change colors in OmenHub it does not reflect any changes on this output. Hence, I assume this might not map to the "Multizone" setting from OmenHub
- GetFanCount: Working
- GetFanLevel: Working
- GetFanTable: Not sure. It returns a table that matches the description, but the values are not reflecting the custom fan table I have setup in OmenHub. Maybe this is the factory fan table - but even then the values are a bit strange, e.g. highest temperature threshold is 50.
- GetGfxMode: Not working(?). Always returns 0x02, no matter which mode is enabled.
- GetGpuStatus: Working
- GetKbdType: Working
- GetTemp: Working(?). Value is lower than reported from other tools, but scales correctly

I hope someone braver than me with the same laptop will try to do the "set" commands and report if they work

**Comment by DarkestOmen** [comment]
* Device: Omen-15 en1xxx  (2021, AMD/nVidia)
* Script Version: 2023-08-22
* Partially working. The max TGP of my 3060 is 100W. I extracted and ran the boot task. The scheduled task was created successfully. However the TGP in any game hovers around 94W and dips sometimes. How can I run it at 100W almost all the time. Also can you animate the keyboard backlit with the script and run it in conjugation with the max tgp script?

**Comment by cyxnzb** [comment]
Device: Omen 16-wf0000  (2023, Intel/nVidia)
Version: 2023-08-22
- Not Working:
- -GetThermalThrottlingStatus：Failed: Error 6

**Comment by rogue-ent** [comment]
* Device: OMEN 17-ck1003nr (2023 | intel/nvidia)
* Script Version: 2023-08-22
* Working:

    BacklightOn/Off

    MaxFanSpeedOn/Off

    SetColor4 (at first it kept telling me the syntax was incorrect, i thought the <> were part of the syntax)    

* Not sure:   

    any get command because i dont understand what any of it means. since it just seems to output hex codes or something

    the gpu power commands, im 99% sure they work at least i set it to max and it did give me a big boost in performance, didnt try the others and i feel like id have no real way to tell if it really is the absolute max/mid/min anyway since i dont understand all the codes
   
    OmenKeyOn/Off (i think but i uninstalled omen gaming hub so it doesnt do anything, couldnt test it)

    SetMemXmp - i did this, it said it worked but idk how to check if its actually on

* Not Working:

    didnt find anything that 100% didnt work

the rest of the commands i didnt test i dont want to mess around with stuff that i dont understand and wouldnt know how to fix like the cpu and fan stuff

**Comment by GeographicCone** [comment]
@rogue-ent (I've answered you in the other thread) and also @cyxnzb, @DarkestOmen, @dd871, @Dragofagnir: thank you all for your feedback on **OmenHwCtl**.

As a heads-up, I've just released **OmenMon**, a C# application that has 100% of **OmenHwCtl**'s functionality and much more. If you want to check it out it's at [omenmon.github.io](https://omenmon.github.io/) and [github.com/OmenMon](https://github.com/OmenMon).

In particular, running `OmenMon -Bios` gives all the information **OmenHwCtl** could retrieve but in a clearer format:

![OmenMon -Bios](https://omenmon.github.io/pic/cli-bios.png)

**Comment by Arjun-Y-Bhardwaj** [comment]
Omen 16 3070ti here
-fans customization working
-backlight on off working
-omen key isn't doing anything even though tried on/off 
help

**Comment by isachko** [comment]
Vitctus 16 16-e1xxxx 
Ryzen 7 6800H, Geforce RTX 3050. DDR5!!!
Not working at all.
Showing temperature and RPM's, but not changing  anything.

------------------
OmenMon Hardware Monitoring & Control Utility Version 0.61-Release
BIOS (-Bios)
- Born-On Date: 20220219 [YYYYMMDD]
- System Design Data: c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 []
- Status Flags: 0x00c8 = 0b0000000011001000 = 200 [BiosPerfPpab3, BiosPerf6, BiosPerf7]
- Unknown Byte: 0x00 = 0b00000000 = 0 [Observed Constant 0x35 = 53]
- Thermal Policy Version: 0x00 = 0b00000000 = 0 [V0]
- Support Flags: 0x00 = 0b00000000 = 0 [0]
- Default CPU Power Limit 4: 0x00 = 0b00000000 = 0 [W]
- BIOS-Defined Overclocking: 0x00 = 0b00000000 = 0 [NotSupported]
- Graphics Mode Switching Support: 0x00 = 0b00000000 = 0 [0]
- Default CPU Concurrent Power Limit w/GPU: 0x00 = 0b00000000 = 0 [W] [Cybug 23C1 Onwards]
- GPU Custom Total Graphics Power (cTGP): 0x01 = 0b00000001 = 1 [On]
- GPU Processing Performance AI Boost (PPAB): 0x01 = 0b00000001 = 1 [On]
- GPU Device Power State (DState): 0x01 = 0b00000001 = 1 [D1]
- GPU Peak Temperature Sensor Threshold: 0x00 = 0b00000000 = 0 [°C]
- Graphics Mode (Legacy): 0x00 = 0b00000000 = 0 [Hybrid]
- Smart Power Adapter Status: 0x01 = 0b00000001 = 1 [MeetsRequirement]
- Overclocking Support: 0x00 = 0b00000000 = 0
- Memory Overclocking Support: 0x00 = 0b00000000 = 0
- BIOS Undervolt Support: 0x00 = 0b00000000 = 0
- Keyboard Type: 0x00 = 0b00000000 = 0 [Standard]
- Keyboard Backlight Support: No
- Keyboard Backlight: 0x80 = 0b10000000 = 128
- Keyboard Backlight Color Table: 4 Zones - Right: 000000, Middle: 000000, Left: 000000, Wasd: 000000
Exception: BIOS call failed: Command not available

OmenMon: Void Check(Int32, Boolean)
   at OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
   at OmenMon.Hardware.Bios.BiosCtl.GetAnimTable()
   at OmenMon.AppCli.CliOp.BiosGetStruct[TResult](String message, Func`1 biosMethod, String extra)
   at OmenMon.AppCli.CliOp.Loop(String[] args)
   at OmenMon.AppCli.CliOp.Loop(String[] args)
   at OmenMon.App.Main(String[] args)

**Comment by CeoAnonymouse** [comment]
16-r1022nt (9J224EA)
9J224EA i7 14700HX 16GB RAM 1TB SSD RTX 4070 

not working fan speed

**Comment by gputhread** [comment]
Victus 15 FB3011AX 8645HS RTX 3050
-Turbo Mod Works while levels dont work
